### ISSUE TITLE
ADO UI publish

### ISSUE THREAD

**Issue by argeualcantara** [maciejmaciejewski/azure-pipelines-cucumber#11]
does this cucumber task publishes the html result in azure devops interface like the [`PublishTestResults@2`](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#yaml-snippet) task does?
example:
this Tests tab in red
![image](https://user-images.githubusercontent.com/2798012/81608101-1a1d3080-93ac-11ea-9fd9-034f9bcb9a44.png)

**Comment by maciejmaciejewski** [comment]
It generates the report from your JSON an then attaches it as a tab in your build or release summary. Uploading HTML is not yet supported, it is one of the feature request.
I hope this answers your question.

**Comment by argeualcantara** [comment]
thank you
