### ISSUE TITLE
Do we need nodeJS on agent to use this task?

### ISSUE THREAD

**Issue by majidmakhdomi** [maciejmaciejewski/azure-pipelines-cucumber#13]
Hi Maciej,

I have run cucumber tests for my Java app using maven. The results are available in a json file in target directory. But when I run PublishCucumberReport@1 after the maven task it fails with the following error:

_Error: Unable to locate executable file: 'npm'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable._

Are there any pre-requisites that we need on the agent?

**Comment by maciejmaciejewski** [comment]
Hello @majidmakhdomi 
Yes node is required to generate the report, I will add this to the documentation.
You can find more details in my response in #9

**Comment by majidmakhdomi** [comment]
Thank you! It is clear now.
