### ISSUE TITLE
getting cucumber json file from multiple azure agents

### ISSUE THREAD

**Issue by abhigyajain** [maciejmaciejewski/azure-pipelines-cucumber#22]
Hi Maciej Maciejewski ,

I have an azure pipeline that has 2 different stages, each stage running a job on a separate azure agent. By using your plugin , i am able to produce cucumber json for each job on its respective agent. 
However on the azure UI, under the cucumber tab, the cucumber results show only the results from 1 json file , it does not show results for the other json file created on another agent.

How does the plugin pick up cucumber results from the agent ? does it only go to 1 agent and not to all the agents for that pipeline ?

**Comment by maciejmaciejewski** [comment]
Hello, this is a known issue that is being worked on, please refer to #19 for more details

**Comment by maciejmaciejewski** [comment]
Should be fixed by #45, new version has been released so please check it and close the issue if solution fits your needs.
