### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by varunpradhan** [maciejmaciejewski/azure-pipelines-cucumber#23]
Thanks for the plugin. It's awesome.

I just wanted a feature that I need this cucumber report to to emailed to a configured user id.

**Comment by maciejmaciejewski** [comment]
This is actually a really nice idea. It will take some time to implement, for the time being you can have a look at [Send email](https://marketplace.visualstudio.com/items?itemName=rvo.SendEmailTask) task and try adding my report as an attachment.
