### ISSUE TITLE
Publish Cucumber report as public

### ISSUE THREAD

**Issue by pujaverma89** [maciejmaciejewski/azure-pipelines-cucumber#25]
Hi Maciej , 

First of all thanks for this extension. I have got a question (may be a stupid one since i am a beginner), I can see the reports being published while i am logged in , but the cucumber test result tab is not publicly viewable. 

How can i make the reports viewable to public ? ( My repo is public and pipeline test results are publicly viewable).

Thanks in advance. 

Best Regards,
Puja Verma

**Comment by maciejmaciejewski** [comment]
Hey @pujaverma89 

By default azure devops projects are set to private, thus you wont be able to see anything unless logged in. You can change given project to public in options, which should give an ability to be used publicly.

![image](https://user-images.githubusercontent.com/15831316/103480664-d2816400-4dd5-11eb-93f1-3acf0d44d771.png)

**Comment by maciejmaciejewski** [comment]
Not related to the project, closing for inactivty.
