### ISSUE TITLE
Minimum Agent Version

### ISSUE THREAD

**Issue by fernando017** [maciejmaciejewski/azure-pipelines-cucumber#26]
Hello!
Thank you so much by creating this extension! 
I have something that I believe will help other users when use it in a Azure DevOps Server Self-Hosted Agent.

First time I tryed to run your extension got this message:

A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)

Then I created a new agent based on x84, and the error switched to:

A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X84)

After a little research, I read your comment in another issue about Node10 version, and even the server having version 12, I updated the nodejs to version 14 and still not worked. Looking about Self-Hosted Agents release notes I found that only agents version 2.144+ are capable of running Node10 extensions, then I updated my agent version and it worked!

To help other users, please update in **task.json** file the "minimumAgentVersion" property to 2.144.0 and they will could check more quickly about this problem and not waste any time looking for it!

Thanks again!

**Comment by maciejmaciejewski** [comment]
Hey @fernando017 

Thank you for the analysis, I will update minimum agent version accordingly.

Regards,
Maciej
