### ISSUE TITLE
Wildcard support?

### ISSUE THREAD

**Issue by miranro** [maciejmaciejewski/azure-pipelines-cucumber#3]
Hey, 

Does this support wildcard? Like **/cucumber/

**Comment by maciejmaciejewski** [comment]
Hello @miranro 
Unfortunately this is not possible as of today, because underlying HTML reporter does not support it.
I will try making a PR to this reporter in order to extend Extension capabilities.

**Comment by maciejmaciejewski** [comment]
New version 1.0.4 has been released containing following enhancement request.
