### ISSUE TITLE
Publishing multiple reports

### ISSUE THREAD

**Issue by PrateekChauhan0194** [maciejmaciejewski/azure-pipelines-cucumber#30]
Hello,

Firstly, I'd like to take a moment to thank you for the amazing plugin.
I have a different case, I'm having 2 different jobs that run in parallel in the pipeline. Both of these jobs have steps to publish the cucumber report. Is there any way to visualise both of these reports in azure devops?

Best regards,
Prateek

**Comment by yechenchao** [comment]
I have a similar issue, if anyone found a solution, please share, thanks.

**Comment by maciejmaciejewski** [comment]
This issue is a duplicate, use to #19 to track the progress.
