### ISSUE TITLE
Invalid Cucumber JSON file

### ISSUE THREAD

**Issue by grajk88** [maciejmaciejewski/azure-pipelines-cucumber#35]
Hi,

I have configured the details required correctly. After the run, I am getting the below error.

Error: Invalid Cucumber JSON file found under /Users/runner/work/1/s/target: /Users/runner/work/1/s/target/cucumber.json

Please can anyone help me in fixing this?

**Comment by maciejmaciejewski** [comment]
Please have a look at #16
