### ISSUE TITLE
Format JSON Requests and Responses

### ISSUE THREAD

**Issue by adrian-85** [maciejmaciejewski/azure-pipelines-cucumber#49]
I'm not sure if this would do it, or more work would be needed.  Just wanting to "pretty" format the JSON request and response bodies for easier navigation when looking at failures.

![image](https://user-images.githubusercontent.com/92115978/158487134-93b1f619-31d4-485e-86a8-7bbadd433e59.png)

**Comment by adrian-85** [comment]
@maciejmaciejewski Is this tool still under active development?

**Comment by maciejmaciejewski** [comment]
@adrian-85 It is, but as the main developer I am struggling to find enought spare time to work on it 😞

**Comment by maciejmaciejewski** [comment]
I am fixing the release pipeline to close multitab contribution so I will include it.

**Comment by maciejmaciejewski** [comment]
resolved by #50

**Comment by adrian-85** [comment]
Thank you @maciejmaciejewski !  I did try to open a PR, but seems I don't have permission?  Maybe I just setup my personal token incorrectly.

And yes, you definitely need more contributors.  My company is using your tool pretty heavily.  I'll mention the need for help, see if I can get you a few more bodies.
