### ISSUE TITLE
Mark Cucumber HTML Report as public in the Azure DevOps Marketplace

### ISSUE THREAD

**Issue by megaflex** [maciejmaciejewski/azure-pipelines-cucumber#5]
Hi Maciej,
I came across your plugin and I want to try it out in my organizations' Azure DevOps subscription. Unfortunately the organization has chosen for a policy where users cannot download any extension. These have to approved first, for that process it is mandatory that the extensions are public and not in preview. 
Could you mark the extension as public?

**Comment by maciejmaciejewski** [comment]
@megaflex 
New version has been pushed to marketplace
