### ISSUE TITLE
Pipelines Stoped Work after extension update

### ISSUE THREAD

**Issue by mpgalo** [maciejmaciejewski/azure-pipelines-cucumber#71]
Hi.

We have a onPremises AzureDevOps wich we use the azure-pipelines-cucumber. After the automatic update of the extension to the version 1.0.9 on march, 19, the pipelines stoped work and give us the following message on the Publish Cucumber Report Task:

`npm ERR! code ETARGET
npm ERR! notarget No matching version found for cucumber-html-reporter@5.5.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
`

We try to update the npm on the build server without result.

Is there a way to use the previous version? Or maybe someone could provide useful information about the extension update that canhelp us to resolve that problem.

Thanks!

**Comment by gholtzhausen** [comment]
We are experiencing  the same problem.
Has anyone found a resolution

**Comment by mpgalo** [comment]
We had to add shell script command to publish cucumber report manually
